# Generated by Django 5.0.6 on 2024-07-18 16:57

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_appliance_name_alter_appliance_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(default='Refrigerator', max_length=100),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='user',
            field=models.OneToOneField(default=monitoring.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
